# Numpy Exercise

>- Load entire file **Lotto.txt** into one array.
>- Sort each row, from smallest number to largest
>- Save the sorted array to a file called lotto_sorted.txt
>- Print to the screen all unique numbers in the array and the count of each unique numbe
>- Export your notebook as firstname_lastname_CIS9650_HW.ipbny
>- Upload the notebook and lotto_sorted.txt to this assignment


In [1]:
import numpy as np

In [8]:
#Load entire file into one array
lotto_arr = np.loadtxt("C:\\Users\\aless\\Desktop\\Zicklin\\Programming For Analytics\\Exercises\\lotto.txt", int)
lotto_arr

array([[17, 22, 36, 37, 52, 24],
       [14, 22, 52, 54, 59,  4],
       [ 5,  8, 29, 37, 38, 24],
       ...,
       [30, 47, 57, 66, 69,  3],
       [ 5, 25, 26, 44, 66,  9],
       [20, 32, 52, 66, 69, 23]])

In [9]:
#Sort each row, from smallest number to largest
lotto_arr_srt = np.array(lotto_arr)
lotto_arr_srt.sort()
lotto_arr_srt

array([[17, 22, 24, 36, 37, 52],
       [ 4, 14, 22, 52, 54, 59],
       [ 5,  8, 24, 29, 37, 38],
       ...,
       [ 3, 30, 47, 57, 66, 69],
       [ 5,  9, 25, 26, 44, 66],
       [20, 23, 32, 52, 66, 69]])

In [10]:
#Save the sorted array to a file called lotto_sorted.txt
np.savetxt('lotto_sorted.txt', lotto_arr_srt, fmt ='%d')

In [11]:
#Print to the screen all unique numbers in the array
lotto_arr_srt_unique = np.unique(lotto_arr_srt)
lotto_arr_srt_unique

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69])

In [12]:
#Print the count of each unique number
count = np.size(lotto_arr_srt_unique)
print(count)

69
